<a href="https://colab.research.google.com/github/cloudhood/applying-math-python-2e/blob/main/notebooks/ch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 1: An Introduction to Basic Packages, Functions, and Concepts

In [2]:
import numpy as np
import scipy as sp

## Decimal Type

In [3]:
from decimal import Decimal

In [4]:
1.1 + 1.563 # Small error from being limited to finite sum of powers of 2.

2.6630000000000003

In [5]:
# Uses IBM general decimal arithmetic spec - using powers of 10.
# Less memory efficient as it stores decimal digits rather than bits.
n1 = Decimal('1.1')
n2 = Decimal('1.563')
n1 + n2

Decimal('2.663')

In [6]:
from decimal import getcontext

# More fine-grained control over precision, display and attributes.
ctx = getcontext()

# Decimal('1.4641')
num = Decimal('1.1')
print(num ** 4)

# Decimal('1.464')
ctx.prec = 4 # set new precision. default = 28.
print(num ** 4)

1.4641
1.464


In [7]:
from decimal import localcontext
num = Decimal("1.1")

# Set context locally
with localcontext() as ctx:
    ctx.prec = 2
    print(num ** 4) # Decimal('1.5')

# Original environment restored
num ** 4  # Decimal('1.4641')

1.5


Decimal('1.464')

In [8]:
from fractions import Fraction

# For applications that need accurate representations of integer fractions,
# like proportions or probabilities, the Fraction type ise useful.
num1 = Fraction(1, 3)
num2 = Fraction(1, 7)
num1 * num2  # Fraction(1, 21)

Fraction(1, 21)

## Functions

In [9]:
# Complex numbers
import cmath

assert (1j) ** 2 == -1
assert (1 + 1j) + 2 == (3 + 1j)
assert (1 + 1j).conjugate() == (1 - 1j)
assert cmath.sqrt(-1) == 1j

t = 50
assert cmath.exp(t * 1j) == cmath.cos(t) + 1j * cmath.sin(t)

In [10]:
# Math functions implemented in C.
import math

print(math.sqrt(4))
print(math.log(10))
print(math.log(10, 10))
print(math.gamma(10))
print(math.erf(3)) # Gaussian error

2.0
2.302585092994046
1.0
362880.0
0.9999779095030014


In [11]:
math.comb(5, 2) # Number of ways to choose 2 items from 5 without replacement

10

In [12]:
math.factorial(10)

3628800

In [13]:
math.gcd(2, 4) # Greatest common divisor

2

In [14]:
math.gcd(4, 3)

1

In [15]:
nums = [.1] * 10

print(sum(nums))

# Addition on an iterable of numbers - keeps track of sums at each step
# to reduce errors.
print(math.fsum(nums)) 

0.9999999999999999
1.0


In [16]:
print(math.isclose(1, .9999999))
print(math.isclose(1, .99999999))
print(math.isclose(1, .999999999))

False
False
True


# NumPy
* High-performance array types and routines for manipulating arrays. 
* Forms the base for numerical and scientific Python stack.
* Uses low-level libraries like BLAS under the hood.

In [17]:
# To apply functions to a large collection of data simultaneously, better to use 
# math.* equivalents in NumPy - more efficient for working with arrays. 
arr = np.array([1, 2, 3, 4]) 
arr

array([1, 2, 3, 4])

In [18]:
# Basic type if the `ndarray` type (NumPy array), which wraps around an underlying
# C array structure. Must consist of homogeneous data.
print(type(arr))
print(np.array([1, 2, 3, 4], dtype=np.int8))
print(np.array([1, 2, 3, 4], dtype=np.float32))

<class 'numpy.ndarray'>
[1 2 3 4]
[1. 2. 3. 4.]


In [19]:
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.dtype) # int64
arr.dtype = np.float32
print(arr)

arr = np.array([1, 2, 3, 4])
print(arr)
arr = arr.astype(np.float32)
print(arr)
# [1. 2. 3. 4.]

[1 2 3 4]
int64
[1.e-45 0.e+00 3.e-45 0.e+00 4.e-45 0.e+00 6.e-45 0.e+00]
[1 2 3 4]
[1. 2. 3. 4.]


In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(10, dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [22]:
# `getitem` protocol
arr = np.array([1, 2, 3, 4])
print(arr[0])  # 1
print(arr[2])  # 3

1
3


In [23]:
first_two = arr[:2] 
even_idx = arr[::2] # start:stop:step
print(first_two)
print(even_idx)

[1 2]
[1 3]


In [24]:
# ufuncs (universal functions) are routines that can operate efficiently in
# NumPy array types. Analogs of math.*.

arr_a = np.array([1, 2, 3, 4])
arr_b = np.array([1, 0, -3, 1])
print(arr_a + arr_b)   # array([2, 2, 0, 5])
print(arr_a - arr_b)   # array([0, 2, 6, 3])
print(arr_a * arr_b)   # array([ 1, 0, -9, 4])
print(arr_b / arr_a)   # array([ 1. , 0. , -1. , 0.25])
print(arr_b ** arr_a)  # array([1, 0, -27, 1])

[2 2 0 5]
[0 2 6 3]
[ 1  0 -9  4]
[ 1.    0.   -1.    0.25]
[  1   0 -27   1]


In [25]:
# Array creation - generate arrays of numbers at regular intervals between two
# given endpoints using np.arange or np.linspace. The latter generates a number
# of values with equal spacing between two endpoints (inclusive) while the former
# generates numbers at a given step size up to but excluding the upper limit.
print(np.linspace(0, 1, 10))
print(np.arange(0, 1, 0.1))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [26]:
# Higher-dimensional arrays can be created by nested lists. The number of nested
# lists represents the number of dimensions of an array.
mat = np.array([[1, 2], [3, 4]])
print(mat.shape)

(2, 2)


In [27]:
# Tensors are arrays with three or more dimensions. In fact, one might call any
# sized array a tensor: 
#    * a vector (one-dimensional array) is a 1-tensor; 
#    * a two-dimensional array is a 2-tensor or matrix.
vec = np.array([1, 2])
print(mat.shape)
print(vec.shape)

(2, 2)
(2,)


In [28]:
# Reshape - total number of elements remains unchanged.
mat.reshape(4,)

array([1, 2, 3, 4])

In [29]:
# Higher-dimensional array.
mat1 = [[1, 2], [3, 4]]
mat2 = [[5, 6], [7, 8]]
mat3 = [[9, 10], [11, 12]]
arr_3d = np.array([mat1, mat2, mat3])
arr_3d.shape #  (outermost, ..., innermost)

(3, 2, 2)

In [30]:
# Element access
mat = np.array([[1, 2], [3, 4]])
print(mat)
print(mat[0, 0])
print(mat[0, 1])
print(mat[:, 1])
print(arr_3d[1, 1, 1])
print(arr_3d[2, 1, 1])

[[1 2]
 [3 4]]
1
2
[2 4]
8
12


In [31]:
np.zeros((3, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [32]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# The transpose function does not actually modify the data in the underlying 
# array but instead changes the shape and an internal flag that indicates the 
# order of stored values to be from row-contiguous (C style) to 
# column-contiguous (F style). This makes the operation very cheap.
A = np.array([[1, 2], [3, 4]])

assert np.array_equal(A.transpose(), A.T)
assert np.array_equal(A.T, np.array([[1, 3], [2, 4]]))

In [50]:
# Trace = sum of leading diagonal
assert A.trace() == 5
assert np.array([[3, 4], [4, 10]]).trace() == 13

In [90]:
# Matrix multiplication
A = np.array([
    [1, 2], 
    [3, 4]
])
B = np.array([
    [-1, 1], 
    [0, 1]
])
print(A @ B)
#     array([[-1, 3],
#            [-3, 7]])
print(A * B) # different from A @ B
#    array([[-1, 2],
#           [ 0, 4]])

assert ~np.array_equal(A @ B, B @ A)

[[-1  3]
 [-3  7]]
[[-1  2]
 [ 0  4]]


In [91]:
# Identity matrix
A = np.array([[1, 2], [3, 4]])
I = np.eye(2)
assert np.array_equal(A @ I, A)
assert np.array_equal(A @ I, I @ A)

In [92]:
# Determinant
#
# The determinant of a square matrix is important due to its strong link with 
# finding the inverse of a matrix. A matrix with a nonzero determinant has a
# unique inverse, leading to unique solutions of certain systems of equations.
# The determinant of a matrix is defined recursively. For a 2x2 matrix A:
#
# det(A) = a_{1,1}a_{2,2} - a{1,2}a{2,1}
print(np.linalg.det(A))
print(np.linalg.inv(A))

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [95]:
Ainv = np.linalg.inv(A)
assert np.isclose(Ainv @ A, np.eye(2)).all()
assert np.isclose(A @ Ainv, np.eye(2)).all()

In [96]:
# Systems of linear equations
#
#  Ax = b
#
#  3x_1 - 2x_2 +  x_3 =  7
#   x_1 +  x_2 - 2x_3 = -4
# -3x_1 - 2x_2 +  x_3 =  1
A = np.array([[3, -2, 1], [1, 1, -2], [-3, -2, 1]])
b = np.array([7, -4, 1])
print(np.linalg.det(A) != 0)
print(np.linalg.solve(A, b))  # Decomposes A into simpler matrices
print(np.linalg.inv(A) @ b)   # Slower and more error prone

True
[ 1. -1.  2.]
[ 1. -1.  2.]


In [97]:
# Eigenvalues and eigenvectors
#
# If A is a square matrix, x a vector and lambda a number, the numbers lambda 
# for which there is an x that solves A x = lambda x are called eigenvalues
# and the corresponding vectors x are called eigenvectors.
A = np.array([[3, -1, 4], [-1, 0, -1], [4, -1, 2]])
v, B = np.linalg.eig(A)

# First eigenvalue/eigenvector pair
i = 0 

lambda0 = v[i]
print(lambda0)

x0 = B[:, i] # ith column of B
print(x0) # Normalized so that they have a norm of 1.
assert np.linalg.norm(x0) == 1

6.823156164525971
[ 0.73271846 -0.20260301  0.64967352]


In [98]:
lhs = A @ x0
rhs = lambda0 * x0
print(np.linalg.norm(lhs - rhs)) # Distance between lhs and rhs
assert np.isclose(lhs, rhs).all()

2.8435583831733384e-15


In [ ]:
# To find eigenvalues and eigenvectors, you first need to find lambda such that
#                           det(A - lambda I) = 0
# The equation determined by the lhs is a polynomial in lambda called the
# characteristic polynomial of A. The eigenvector corresponding to the eigenvalue
# lambda_i can then be found by solving:
#
#                           (A - lambda_j I)x = 0
